### ISSUE TITLE
能增加一个在线pac功能不，对于懒人来说，一个能在线实时更新的pac很又必要的

### ISSUE THREAD

**Issue by maryjeck** [nobody3u/VGCPlugins#1]

**Comment by maryjeck** [comment]
https://raw.githubusercontent.com/petronny/gfwlist2pac/master/gfwlist.pac
这是一个更新比较勤快的pac

**Comment by nobody3u** [comment]
没这打算，感觉没必要经常更新。
我通常几个月才更一次也没发现哪些网站访问不了。
